version: 2.1
insights:
  performance: true

jobs:
  test:
    docker:
      - image: circleci/openjdk:17.0-jdk-buster

    working_directory: ~/code-build-test
    environment:
        # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout:
          branch: circleci-project-setup
      - restore_cache:
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run: ./gradlew test
      - store_test_results:
          path: build/test-results/test

      - save_cache:
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - .gradle/

  build:
    docker:
      - image: circleci/openjdk:17.0-jdk-buster

    working_directory: ~/code-build-test
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout:
          branch: circleci-project-setup

      - restore_cache:
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run: ./gradlew build
      - save_cache:
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - .gradle/

      - store_artifacts:
          path: build/libs
      # docker build를  하기 위해 docker를 이미 설치한다.
      - setup_remote_docker:
          version: 19.03.13
      - run: docker build --build-arg JAR_FILE=build/libs/code-build-test-0.0.1-SNAPSHOT.jar --tag roseoutz/test:latest .
      - run: docker login -u roseoutz -p rose2391@
      - run: docker push roseoutz/test:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
        requires:
          - build