version: 2.1
insights:
  performance: true

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  gradle: circleci/gradle@3.0.0

executors:
  build-executor:
    docker:
      - image: circleci/openjdk:17.0-jdk-buster
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
  
jobs:
  test-build:
    executor: build-executor
    working_directory: ~/code-build-test
    steps:
      - checkout
      - restore_cache:
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run: ./gradlew test
      - store_test_results:
          path: build/test-results/test

      - run: ./gradlew build
      - save_cache:
          key: gradle-cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - .gradle/
      - store_artifacts:
          path: build/libs/
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build-deploy:
    when:
      or:
      - equal: [ circleci-project-setup, << pipeline.git.branch >> ]
    jobs:
      - test-build
      - aws-ecr/build-and-push-image:
          name: push-image
          requires:
            - test-build
          context: AWS_CREDENTIAL
          checkout: false
          attach-workspace: true
          workspace-root: .
          repo: '${SERVICE_NAME}'
          tag: 'latest,${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          name: deploy-service
          requires:
            - push-image
          context: AWS_CREDENTIAL
          cluster: '${SERVICE_NAME}'
          family: '${SERVICE_NAME}-task'
          container-image-name-updates: 'container=${SERVICE_NAME},tag=${CIRCLE_SHA1}'