version: 0.2  # 0.2 권장

phases:   # 빌드 단계
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version
      - gradle -version
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - REPOSITORY_URI=$AWS_ECR_URL
      - IMAGE_TAG=$AWS_ECR_IMAGE_TAG
  build:
    commands:
      - echo Test Start
      - ./gradlew test
  post_build:
    commands:
      - echo Build Start
      - ./gradlew bootJar
artifacts:
  files:
    - build/libs/code-build-test-0.0.1-SNAPSHOT.jar  # 업로드 할 파일들
  discard-paths: yes # 파일명 기준으로만 업로드

reports:
  junit:
    - '**/test-results/**/*.xml'