version: 0.2  # 0.2 권장

phases:   # 빌드 단계
  install:
    runtime-versions:
      java: corretto17
    commands:
      - java -version
      - gradle -version
  build:
    commands:
      - echo Test Start
      - ./gradlew test
  post_build:
    commands:
      - echo Build Start
      - ./gradle bootJar
artifacts:
  files:
    - build/libs/code-build-test-0.0.1-SNAPSHOT.jar  # 업로드 할 파일들
  discard-paths: yes # 파일명 기준으로만 업로드
cache:
  paths:
    - '/root/.m2/**/*'   # S3 cache에 등록할 파일들